### ISSUE TITLE
Expose Barbara's 2nd Field in her Profile

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/University-Community-Collaborative#8]
Please expose Barbara's second field as Director for this center only not her PolySci profile. Thanks WC!

**Comment by tu-chill** [comment]
wlll expose both

**Comment by tu-chill** [comment]
Editing a view for a center. did something that will surely be lost. I added the second title field and set it to exclude from the display. Next, I hi-jacked the faculty title field and set it to rewrite and strip out HTML for the second title field. So now it only lists WAIT now I added the faculty title field under the secondary field so that the others aren't blank. though the others don't seem like faculty at all and the titles are not faculty titles. hmmm.
